### ISSUE TITLE
Support streaming requests through HTTPoison

### ISSUE THREAD

**Issue by edevil** [scrogson/oauth2#42]
The underlying HTTP library, HTTPoison/Hackney, supports asynchronous requests but it seems that this library is not ready for them.

For example, in the case of response streaming:
```
 > OAuth2.AccessToken.get(token, "/1/Files/meocloud/output.m4a", [], [hackney: [:insecure, {:async, :once}]])
** (CaseClauseError) no case clause matching: {:ok, %HTTPoison.AsyncResponse{id: #Reference<0.0.2.3515>}}
        (oauth2) lib/oauth2/request.ex:16: OAuth2.Request.request/5
        (oauth2) lib/oauth2/access_token.ex:221: OAuth2.AccessToken.request/6
...
```

It would be nice to support both response and request streaming. Or at least be able to generate the correct headers for a request so that we could drive HTTPoison ourselves.

**Comment by edevil** [comment]
Does this mean that this feature is not planned?
