### ISSUE TITLE
Weird error :noproc

### ISSUE THREAD

**Issue by bradurani** [scrogson/oauth2#55]
I've copied and pasted the code from the demo app into my own app, and with both GitHub and Google I'm getting this error on the call to  `OAuth2.Client.get_token!(client(), params)`
```
[error] #PID<0.422.0> running Dashboard.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /auth/google/callback?code=4/8GTqlaN6ZY1GtJWJuUMxntdNgCL6Z3k3bC8GyJtVAUE
** (exit) an exception was raised:
    ** (OAuth2.Error) {:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.422.0>, #Reference<0.0.1.2735>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_ssl_transport, 'accounts.google.com', 443, "accounts.google.com", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, ...}}, :infinity]}}
        lib/oauth2/client.ex:171: OAuth2.Client.get_token!/4
        (dashboard) web/controllers/auth_controller.ex:27: Dashboard.AuthController.callback/2
        (dashboard) web/controllers/auth_controller.ex:1: Dashboard.AuthController.action/2
        (dashboard) web/controllers/auth_controller.ex:1: Dashboard.AuthController.phoenix_controller_pipeline/2
        (dashboard) lib/phoenix/router.ex:261: Dashboard.Router.dispatch/2
        (dashboard) web/router.ex:1: Dashboard.Router.do_call/2
        (dashboard) lib/dashboard/endpoint.ex:1: Dashboard.Endpoint.phoenix_pipeline/1
        (dashboard) lib/plug/debugger.ex:93: Dashboard.Endpoint."call (overridable 3)"/2
        (dashboard) lib/phoenix/endpoint/render_errors.ex:34: Dashboard.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Any help appreciated!

**Comment by bradurani** [comment]
I should probably have mentioned that with `0.6.0`

**Comment by bradurani** [comment]
Here's a script that reproduces the problem with `0.5.0`
```ex
params = [code: "XXXXXXXXXXXXXXXXXX"]
config = [authorize_url: "/o/oauth2/auth",
 client_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
 client_secret: "XXXXXXXXXXXXXXXXXX", headers: [], params: %{},
 redirect_uri: "http://localhost:4000/auth/google/callback",
 site: "https://accounts.google.com", strategy: OAuth2.Strategy.AuthCode,
 token_method: :post, token_url: "/o/oauth2/token"]
c = OAuth2.Client.new(config)
OAuth2.Client.get_token!(c, params)
```

**Comment by bradurani** [comment]
Figured it out,

I didn't have the `oauth2` application added to the application list 😩
