### ISSUE TITLE
Arguement error in `to_url`

### ISSUE THREAD

**Issue by spencerldixon** [scrogson/oauth2#93]
I'm trying to put a simple Oauth link on the page, having followed the github example in the docs and come up against this error...

```
 ** (ArgumentError) argument error
        (oauth2) lib/oauth2/client.ex:391: OAuth2.Client.to_url/2
        (oauth2) lib/oauth2/client.ex:201: OAuth2.Client.authorize_url!/2
```

Checking out line 391 leads us to...

```
  defp to_url(client, endpoint) do
    endpoint = Map.get(client, endpoint)
    url = endpoint(client, endpoint) <> "?" <> URI.encode_query(client.params)
    {client, url}
  end
```

And putting in an IEx.pry shows that the `endpoint(client, endpoint)` function seems to be the culprit breaking here.

What's going on here? 😕

**Comment by spencerldixon** [comment]
Fixed it! Ensure you use double quotes for your strings when specifying the `authorize_url` etc. Old ruby habits die hard!
